import type { Metadata } from "next";
import "./globals.css";

// import Toast from "@/_components/Toast";

import Toast from "./_components/Toast";
// import Toolbar from "@/_components/Toolbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // const { toast } = useToast();

  // console.log("%ctoast is", "font-size: 32px");
  // console.log(useToast);
  // console.log("%ctoast finished", "font-size: 32px");

  return (
    <html lang="en" className="center">
      <body>
        {children}
        <Toast />
      </body>
    </html>
  );
}
